/* SQL PROYECTO
    Felipe Calvache - Hernan Sanchez
*/


-- Foraneas

ALTER TABLE TipoProductos
ADD CONSTRAINT FK_TipoProductos_proveedores FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor);

ALTER TABLE PRECIOS
ADD CONSTRAINT FK_precios_proveedores FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor);

ALTER TABLE PRECIOS
ADD CONSTRAINT FK_precios_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto);

ALTER TABLE DetalleDeVentas
ADD CONSTRAINT FK_DetalleDeVentas_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto);

ALTER TABLE DetalleDeVentas
ADD CONSTRAINT FK_DetalleDeVentas_ventas FOREIGN KEY (idVenta) REFERENCES VENTAS(idVenta);

ALTER TABLE DetalleDePedidos
ADD CONSTRAINT FK_DetalleDePedidos_pedidos FOREIGN KEY (idPedido) REFERENCES PEDIDOS(idPedido);

ALTER TABLE DetalleDePedidos
ADD CONSTRAINT FK_DetalleDePedidos_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto);

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_pedidos_proveedores FOREIGN KEY (idProveedor) REFERENCES PROVEEDORES(idProveedor);

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_pedidos_empleados FOREIGN KEY (idEmpleado) REFERENCES EMPLEADOS(idEmpleado);

ALTER TABLE VALORACIONES
ADD CONSTRAINT FK_valoraciones_clientes FOREIGN KEY (idCliente) REFERENCES CLIENTES(idCliente);

ALTER TABLE VALORACIONES
ADD CONSTRAINT FK_valoraciones_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto);

ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_empleados_sedes FOREIGN KEY (idSede) REFERENCES SEDES(idSede);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_ventas_clientes FOREIGN KEY (idCliente) REFERENCES CLIENTES(idCliente);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_ventas_empleados FOREIGN KEY (idEmpleado) REFERENCES EMPLEADOS(idEmpleado);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_ventas_facturas FOREIGN KEY (idFactura) REFERENCES FACTURAS(idFactura);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_ventas_envios FOREIGN KEY (idEnvio) REFERENCES ENVIOS(idEnvio);

ALTER TABLE ELECTRONICAS
ADD CONSTRAINT FK_electronicas_facturas FOREIGN KEY (idFactura) REFERENCES FACTURAS(idFactura);

ALTER TABLE FISICAS
ADD CONSTRAINT FK_fisicas_facturas FOREIGN KEY (idFactura) REFERENCES FACTURAS(idFactura);

