/* SQL PROYECTO
    Felipe Calvache - Hernan Sanchez
*/


-- Primarias

ALTER TABLE TipoProductos
ADD CONSTRAINT PK_TipoProductos PRIMARY KEY (idProveedor, tipoProducto);

ALTER TABLE PROVEEDORES
ADD CONSTRAINT PK_proveedores PRIMARY KEY (idProveedor);

ALTER TABLE PRECIOS
ADD CONSTRAINT PK_precios PRIMARY KEY (idProveedor, idProducto);

ALTER TABLE PRODUCTOS
ADD CONSTRAINT PK_productos PRIMARY KEY (idProducto);

ALTER TABLE DetalleDeVentas
ADD CONSTRAINT PK_DetalleDeVentas PRIMARY KEY (idDetalleVenta, idVenta);

ALTER TABLE DetalleDePedidos
ADD CONSTRAINT PK_DetalleDePedidos PRIMARY KEY (idDetalle, idPedido);

ALTER TABLE PEDIDOS
ADD CONSTRAINT PK_pedidos PRIMARY KEY (idPedido);

ALTER TABLE VALORACIONES
ADD CONSTRAINT PK_valoraciones PRIMARY KEY (idValoracion);

ALTER TABLE CLIENTES
ADD CONSTRAINT PK_clientes PRIMARY KEY (idCliente);

ALTER TABLE EMPLEADOS
ADD CONSTRAINT PK_empleados PRIMARY KEY (idEmpleado);

ALTER TABLE SEDES
ADD CONSTRAINT PK_sedes PRIMARY KEY (idSede);

ALTER TABLE ENVIOS
ADD CONSTRAINT PK_envios PRIMARY KEY (idEnvio);

ALTER TABLE VENTAS
ADD CONSTRAINT PK_ventas PRIMARY KEY (idVenta);

ALTER TABLE FACTURAS
ADD CONSTRAINT PK_facturas PRIMARY KEY (idFactura);

ALTER TABLE FISICAS
ADD CONSTRAINT PK_fisicas PRIMARY KEY (idFactura);

ALTER TABLE ELECTRONICAS
ADD CONSTRAINT PK_electronicas PRIMARY KEY (idFactura);

