/* SQL PROYECTO
    Felipe Calvache - Hernan Sanchez
*/


-- Unicas

ALTER TABLE PROVEEDORES
ADD CONSTRAINT UK_proveedores UNIQUE (correo);

ALTER TABLE EMPLEADOS
ADD CONSTRAINT UK_empleados UNIQUE (correo);

ALTER TABLE SEDES
ADD CONSTRAINT UK_sedes UNIQUE (direccion);

ALTER TABLE CLIENTES
ADD CONSTRAINT UK_clientes_numero UNIQUE (numero);

ALTER TABLE CLIENTES
ADD CONSTRAINT UK_clientes_correo UNIQUE (correo);

