/* SQL PROYECTO
    Felipe Calvache - Hernan Sanchez
*/


-- xPoblar

DELETE FROM PRECIOS;
DELETE FROM VALORACIONES;
DELETE FROM FISICAS;
DELETE FROM ELECTRONICAS;
DELETE FROM DetalleDeVentas;
DELETE FROM DetalleDePedidos;
DELETE FROM PEDIDOS;
DELETE FROM TipoProductos;
DELETE FROM PROVEEDORES;
DELETE FROM VENTAS;
DELETE FROM PRODUCTOS;
DELETE FROM CLIENTES;
DELETE FROM EMPLEADOS;
DELETE FROM SEDES;
DELETE FROM ENVIOS;
DELETE FROM FACTURAS;