/* SQL PROYECTO
    Felipe Calvache - Hernan Sanchez
*/


-- xTablas

DROP TABLE PRECIOS;
DROP TABLE VALORACIONES;
DROP TABLE FISICAS;
DROP TABLE ELECTRONICAS;
DROP TABLE DetalleDeVentas;
DROP TABLE DetalleDePedidos;
DROP TABLE PEDIDOS;
DROP TABLE TipoProductos;
DROP TABLE PROVEEDORES;
DROP TABLE VENTAS;
DROP TABLE PRODUCTOS;
DROP TABLE CLIENTES;
DROP TABLE EMPLEADOS;
DROP TABLE SEDES;
DROP TABLE ENVIOS;
DROP TABLE FACTURAS;